version: "3"

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile-dev
    environment:
      DEVELOPMENT: "true"
      # XDEBUG_CONFIG: remote_host={{YOUR_IP_ADDRESS}}
